email:
  default_sender:
    - Admin
    - admin@localhost.localdomain
  default_recipient:
    - Admin
    - admin@localhost.localdomain

flask:
  ENV: development
  SECRET_KEY: !!binary |
  1XmLnGO8Hrt84UbmKcPdsXd/XhVKTxy1c1gU291hdyKG8xaJK/I/uGowSMzDrf9pqep88PXUm8VM
  AmvfhyCzzg==
  RECAPTCHA_PRIVATE_KEY: "put your private key from recaptcha here"
  RECAPTCHA_PUBLIC_KEY: "put your public key from recaptcha here"
  SERVER_NAME: 127.0.0.1:5000
  SESSION_TYPE: redis
  REDIS_URL: redis://localhost:6379/0
  #  TESTING: true
